function printHTML(dataset, path, url, Tt, Iv, imgIds, concepts, images, r)

path = strcat(path, '/HTML/clusters/');
urlThumbnail = url;
extension = '';

[m n] = size(Tt);

for cluster=1:r
    c = strcat('c', int2str(cluster));
    fid = fopen(strcat(path, c, '.htm'), 'w');
    html = ['<html>'...
    '<head>'...
    '<title>Multimodal summarization (', dataset,')</title>'...
    '</head>'...
    '<body>'...
    '<table width="800" height="299" border="0">'...
    '  <tr>'...
    '    <td><table width="800" border="0">'...
    '      <tr>'...
    '        <td colspan="2" align="center" valign="top"><strong>Cluster ', int2str(cluster),'</strong></td>'...
    '        </tr>'...
    '      <tr>'...
    '        <td width="108" align="left" valign="top">'];
    
    for j=1:concepts
        html = strcat(html, char(Tt(j, cluster)), '<br>');
    end
    

    html = strcat(html, ['</td><td width="676" align="left" valign="top">']);

    for j=1:images
%         b = cellfun(@(str)str2double(str), Iv(j,cluster));
%         c = cellfun(@(str)str2double(str), imgIds);
        %img = imgIds(find(c(:,1)==b(j,cluster),1));
        img = char(Iv(j,cluster));
        html = strcat(html,'<a href="',url, img, extension, '" target="_blank"><img src="', urlThumbnail, img, extension);
        html = strcat(html, '" border="1"></a>');
    end
    
    html = strcat(html, ['</td>'...
    '      </tr>'...
    '    </table></td>'...
    '  </tr>'...
    '</table>'...
    '</body>'...
    '</html>']);

    fprintf(fid, html);
    fclose(fid);
end
